# Generated by Django 4.0.6 on 2022-07-14 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_habit_record_record_unique_record'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='target',
            field=models.IntegerField(null=True),
        ),
    ]
