# Generated by Django 4.0.6 on 2022-07-14 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0003_alter_habit_target'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='target',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='record',
            name='daily_number',
            field=models.IntegerField(null=True),
        ),
    ]
